### ISSUE TITLE
Create learning_topics_tracker table in the project database

### ISSUE THREAD

**Issue by Abubakar-Meigag** [Abubakar-Meigag/FinalProject-DejaReview-teamUnity-Ldn10#23]
**# We will discuss the required column and table structure during the Saturday meeting.**

**Comment by KristinaDudnyk** [comment]
![Image](https://github.com/Abubakar-Meigag/FinalProject-DejaReview-teamUnity-Ldn10/assets/113212730/cc8663b8-ba56-456e-970b-a5b9d89a60cc)

**Comment by KristinaDudnyk** [comment]
![Image](https://github.com/Abubakar-Meigag/FinalProject-DejaReview-teamUnity-Ldn10/assets/113212730/e34e5cf7-b34f-4fd4-90db-4ab1f016b082)
