### ISSUE TITLE
Navigation Side Panel Task

### ISSUE THREAD

**Issue by Abdirizak-Mohamed** [Abubakar-Meigag/FinalProject-DejaReview-teamUnity-Ldn10#25]
**As a user** I want to be presented with a navigation panel
**When I** navigate to the homepage of my application 
**So that I** can navigate between my dashboard and All topics page

### Acceptance
- [x] I can see the unity Logo at the top of my sidepanel
- [x] I can see and use a dashboard option to navigate to dashboard page
- [x] I can see and use the All Topics option to naviage to the all topics page
- [x] [Stretch] It should be obvious which page I am on when I look at the Side panel. e.g. It should be a different color to other option when selected

**Comment by Abubakar-Meigag** [comment]
completed
