### ISSUE TITLE
User Login/Sign Up Functionality

### ISSUE THREAD

**Issue by Abdirizak-Mohamed** [Abubakar-Meigag/FinalProject-DejaReview-teamUnity-Ldn10#32]
**As a user** I want to be able to sign up for Deja Review
**When I** navigate to the homepage 
**So that I** can see a personalised view of the app

### Acceptance
- [x] I can sign up for Deja review
- [x] When I navigate to dashboard for first time after sign up dashboard table should be empty

**Comment by Abubakar-Meigag** [comment]
Here are the steps for implementing user login and sign-up functionality, including storing user information in the project database:

# create an account in Auth0 and setup project application 
- Take the domain from auth0 after I create the application 

# create a new project in the console Google Cloud to integrate with our domain application 
- Take the client ID and Secret to connect with Google login on the Auth0 app.

# code side

# frontend 

- install @auth0/auth0-react for Auth0 React SDK.
- add the Auth0Provider to the react index to manage the root.
- implement useAuth0 hooks for login and logout with navigate to dashboard when are login and to login page when is a logout 
- create a profile page - which also store user info in the project database 

# backend

- implement an endpoint to send user info to the project database
