### ISSUE TITLE
MAKE WIREFRAME || All Modules Page

### ISSUE THREAD

**Issue by kwebster77** [Abubakar-Meigag/FinalProject-DejaReview-teamUnity-Ldn10#8]
As a user, I want to simply:
- navigate on the page 
- see all modules and their topics  
- have the ability to add selected topics to the main dashboard

**Comment by KristinaDudnyk** [comment]
![Image](https://github.com/Abubakar-Meigag/FinalProject-DejaReview-teamUnity-Ldn10/assets/113212730/c1200277-db15-4c08-8dec-544a4b4e6ad7)
